"""Asset manager — resolves and caches downloaded assets for a single execution."""

from __future__ import annotations

from pathlib import Path

import structlog

from worker.config import settings
from worker.models import Layer, LayerType, RenderJob
from worker.storage import StorageClient, TempWorkspace

log = structlog.get_logger(__name__)


class AssetManager:
    """Downloads and tracks all assets required for a render execution.

    All files land in the execution-scoped TempWorkspace so they are
    cleaned up together after the job completes.
    """

    def __init__(self, storage: StorageClient, workspace: TempWorkspace) -> None:
        self._storage = storage
        self._workspace = workspace
        # Maps S3 key → local path
        self._cache: dict[str, Path] = {}

    # ── Public API ────────────────────────────────────────────────────────────

    def download_source_video(self, job: RenderJob) -> Path:
        """Download the source video and return its local path."""
        key = job.source_video_s3_key
        return self._download(settings.input_bucket, key, subdir="assets")

    def download_audio(self, s3_key: str) -> Path:
        """Download a TTS audio asset."""
        return self._download(settings.input_bucket, s3_key, subdir="assets")

    def download_subtitle_ass(self, s3_key: str) -> Path:
        """Download a pre-generated ASS subtitle file."""
        return self._download(settings.input_bucket, s3_key, subdir="assets")

    def download_image_layer_asset(self, layer: Layer) -> Path | None:
        """Download an image/logo asset for an IMAGE-type layer.

        Returns None if the layer has no src set.
        """
        if layer.type not in (LayerType.IMAGE, LayerType.SHAPE):
            return None
        src = layer.content.src
        if not src:
            return None
        # Src can be an S3 key or a presigned URL; we handle keys only
        return self._download(settings.input_bucket, src, subdir="assets")

    def download_all_assets(self, job: RenderJob) -> dict[str, Path]:
        """Download all required assets upfront and return a key→path map."""
        paths: dict[str, Path] = {}

        # Source video
        video_path = self.download_source_video(job)
        paths["source_video"] = video_path

        # TTS audio
        if job.voice_settings.enabled and job.voice_settings.audio_s3_key:
            audio_path = self.download_audio(job.voice_settings.audio_s3_key)
            paths["audio"] = audio_path

        # ASS subtitles (pre-generated by backend)
        if job.subtitle_settings.enabled and job.subtitle_settings.ass_s3_key:
            ass_path = self.download_subtitle_ass(job.subtitle_settings.ass_s3_key)
            paths["subtitles"] = ass_path

        # Image layers
        for layer in job.visible_layers:
            if layer.type in (LayerType.IMAGE, LayerType.SHAPE) and layer.content.src:
                p = self.download_image_layer_asset(layer)
                if p:
                    paths[f"layer:{layer.layer_id}"] = p

        return paths

    # ── Private ───────────────────────────────────────────────────────────────

    def _download(self, bucket: str, key: str, *, subdir: str = "") -> Path:
        cache_key = f"{bucket}/{key}"
        if cache_key in self._cache:
            log.debug("asset_manager.cache_hit", key=key)
            return self._cache[cache_key]

        filename = Path(key).name or key.replace("/", "_")
        local_path = self._workspace.path(subdir, filename) if subdir else self._workspace.path(filename)

        # Avoid name collisions by appending a counter suffix
        if local_path.exists():
            stem = local_path.stem
            suffix = local_path.suffix
            counter = 1
            while local_path.exists():
                local_path = local_path.with_name(f"{stem}_{counter}{suffix}")
                counter += 1

        self._storage.download_file(bucket, key, local_path)
        self._cache[cache_key] = local_path
        return local_path
